[build]
pre-build = [
    "curl -fsSL \"https://github.com/crow-rest/cargo-prebuilt-index/releases/download/cargo-auditable-$(curl -fsSL https://github.com/crow-rest/cargo-prebuilt-index/releases/download/stable-index/cargo-auditable)/x86_64-unknown-linux-musl.tar.gz\" -o ca-musl.tar.gz",
    "tar -xvzf ca-musl.tar.gz -C /bin",
    "echo \\#\\!/bin/sh > /bin/cargo",
    "echo \"export CARGO='/rust/bin/cargo'\" >> /bin/cargo",
    "echo 'cargo-auditable auditable \"$@\"' >> /bin/cargo",
    "chmod +x /bin/cargo"
]
