[target.x86_64-unknown-freebsd]
image = "ghcr.io/cargo-prebuilt/cross-openssl:x86_64-unknown-freebsd"

[target.x86_64-unknown-netbsd]
image = "ghcr.io/cargo-prebuilt/cross-openssl:x86_64-unknown-netbsd"

[target.x86_64-unknown-illumos]
image = "ghcr.io/cargo-prebuilt/cross-openssl:x86_64-unknown-illumos"

[target.x86_64-sun-solaris]
image = "ghcr.io/cargo-prebuilt/cross-auditable:x86_64-sun-solaris"

[target.powerpc64-unknown-linux-gnu]
image = "ghcr.io/cargo-prebuilt/cross-openssl:powerpc64-unknown-linux-gnu"
