name: %%CRATE%% stable build

on:
  push:
    branches: [ trigger/stable ]
  workflow_dispatch:

env:
  index: %%INDEX%%/releases/download/stable-index/
  crate: %%CRATE%%
  version: %%VERSION%%
  license: %%LICENSE%%
  dl: %%DOWNLOAD%%
  checksum: %%CHECKSUM%%
  bins: %%BINS%%
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: DBG - API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /rate_limit
      - name: Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            bundle
            build
          key: ${{ env.crate }}-${{ env.version }}-stable-deps
          enableCrossOsArchive: true
      - name: Create Folders
        if: ${{ !steps.cache.outputs.cache-hit }}
        run: |
          mkdir -p ~/.cargo/registry/index
          mkdir -p ~/.cargo/registry/cache
          mkdir -p ~/.cargo/git/db
          mkdir -p ./bundle
          mkdir -p ./build
      - name: Download crate and check hash
        if: ${{ !steps.cache.outputs.cache-hit }}
        run: |
          wget ${{ env.dl }}
          echo "${{ env.checksum }} ${{ env.crate }}-${{ env.version }}.crate" | sha256sum -c
          tar -xf ${{ env.crate }}-${{ env.version }}.crate
          mv ${{ env.crate }}-${{ env.version }}/* ./build
      - name: Update Rust
        if: ${{ !steps.cache.outputs.cache-hit }}
        run: rustup update
      - name: Rust Version
        if: ${{ !steps.cache.outputs.cache-hit }}
        run: rustc --version
      - name: Generated lockfile if needed
        if: ${{ !steps.cache.outputs.cache-hit }}
        working-directory: ./build
        run: test -f Cargo.lock || cargo +stable generate-lockfile --verbose
      - name: Download Deps
        if: ${{ !steps.cache.outputs.cache-hit }}
        working-directory: ./build
        run: cargo +stable fetch --verbose --locked
      - name: Bundle Deps
        if: ${{ !steps.cache.outputs.cache-hit }}
        run: |
          mkdir -p ./bundle/registry
          mkdir -p ./bundle/git
          cp -r ~/.cargo/registry/index ./bundle/registry
          cp -r ~/.cargo/registry/cache ./bundle/registry
          cp -r ~/.cargo/git/db ./bundle/git

  reports:
    runs-on: ubuntu-latest
    needs: [ setup ]
    steps:
      - uses: actions/checkout@v3
      - name: Get deps and crates from cache
        uses: actions/cache@v3
        with:
          path: |
            bundle
            build
          key: ${{ env.crate }}-${{ env.version }}-stable-deps
          enableCrossOsArchive: true
          fail-on-cache-miss: true
      - name: Move deps
        run: mv ./bundle/* ~/.cargo
      - name: Cache Advisory DB
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/advisory-db
          key: stable-advisory-db
      - name: Update Rust
        run: rustup update
      - name: Rust Version
        run: rustc --version
      - uses: cargo-prebuilt/cargo-prebuilt-action@v1
        with:
          tools: cargo-audit
      - name: Generate reports
        working-directory: ./build
        run: |
          echo "License"
          echo "Generated on: $(date --utc)" > ../license.report && echo "Crates.io license metadata: ${{ env.license }}" >> ../license.report
          echo "Found license texts:" >> ../license.report
          tail -n +1 *LICENSE* >> ../license.report || true
          tail -n +1 *license* >> ../license.report || true
          echo "Audit"
          echo "Generated on: $(date --utc)" > ../deps.report && cargo +stable tree --verbose --locked -e normal,build >> ../deps.report
          echo "Generated on: $(date --utc)" > ../audit.report && cargo audit >> ../audit.report || true
      - name: Output reports
        run: |
          echo "### License:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat license.report >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "### Deps:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat deps.report >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "### Audit:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat audit.report >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
      - name: Store reports
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: "*.report"

  t1-cross:
    strategy:
      fail-fast: false
      matrix:
        target: [ x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl, aarch64-unknown-linux-gnu, aarch64-unknown-linux-musl ]
    env:
      CROSS_CONFIG: ../Cross.toml
    runs-on: ubuntu-latest
    needs: [ setup ]
    steps:
      - uses: actions/checkout@v3
      - name: TODO - REMOVE
        run: exit 1
      - name: Get deps and crates from cache
        uses: actions/cache@v3
        with:
          path: |
            bundle
            build
          key: ${{ env.crate }}-${{ env.version }}-stable-deps
          enableCrossOsArchive: true
          fail-on-cache-miss: true
      - name: Move deps
        run: mv ./bundle/* ~/.cargo
      - uses: actions/cache@v3
        if: ${{ !%%IF%% }}
        with:
          path: |
            build/target
          key: ${{ runner.os }}-${{ env.crate }}-${{ env.version }}-stable-${{ matrix.target }}
      - name: Update Rust
        run: rustup update
      - name: Rust Version
        run: rustc --version
      - uses: cargo-prebuilt/cargo-prebuilt-action@v1
        with:
          tools: cross
      - name: Build crate
        working-directory: ./build
        run: cross +stable build --verbose --release --locked --target ${{ matrix.target }} %%FLAGS%%
      - name: Collect
        run: ./scripts/collect.py ${{ matrix.target }} ./build/target/${{ matrix.target }}/release ${{ env.bins }}
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: target-${{ matrix.target }}
          path: |
            ${{ matrix.target }}.tar.gz
            ${{ matrix.target }}.sha256

  t1-apple-darwin:
    strategy:
      fail-fast: false
      matrix:
        target: [ x86_64-apple-darwin, aarch64-apple-darwin ]
    runs-on: macos-latest
    needs: [ setup ]
    steps:
      - uses: actions/checkout@v3
      - name: Get deps and crates from cache
        uses: actions/cache@v3
        with:
          path: |
            bundle
            build
          key: ${{ env.crate }}-${{ env.version }}-stable-deps
          enableCrossOsArchive: true
          fail-on-cache-miss: true
      - name: Move deps
        run: mv ./bundle/* ~/.cargo
      - uses: actions/cache@v3
        if: ${{ !%%IF%% }}
        with:
          path: |
            build/target
          key: ${{ runner.os }}-${{ env.crate }}-${{ env.version }}-stable-${{ matrix.target }}
      - name: Update Rust
        run: rustup update
      - name: Rust Version
        run: rustc --version
      - name: Add Rust target
        run: rustup target add ${{ matrix.target }}
      - uses: cargo-prebuilt/cargo-prebuilt-action@v1
        with:
          tools: cargo-auditable
      - name: Build crate
        working-directory: ./build
        run: cargo +stable auditable build --verbose --release --locked --target ${{ matrix.target }} %%FLAGS%%
      - name: Collect
        run: ./scripts/collect.py ${{ matrix.target }} ./build/target/${{ matrix.target }}/release ${{ env.bins }}
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: target-${{ matrix.target }}
          path: |
            ${{ matrix.target }}.tar.gz
            ${{ matrix.target }}.sha256

  t2-cross:
    if: %%T2_CROSS_HAS_TARGETS%%
    strategy:
      fail-fast: false
      matrix:
        target: [ %%T2_CROSS_TARGETS%% ]
    env:
      CROSS_CONFIG: ../Cross.toml
    runs-on: ubuntu-latest
    needs: [ setup ]
    steps:
      - uses: actions/checkout@v3
      - name: Get deps and crates from cache
        uses: actions/cache@v3
        with:
          path: |
            bundle
            build
          key: ${{ env.crate }}-${{ env.version }}-stable-deps
          enableCrossOsArchive: true
          fail-on-cache-miss: true
      - name: Move deps
        run: mv ./bundle/* ~/.cargo
      - uses: actions/cache@v3
        if: ${{ !%%IF%% }}
        with:
          path: |
            build/target
          key: ${{ runner.os }}-${{ env.crate }}-${{ env.version }}-stable-${{ matrix.target }}
      - name: Update Rust
        run: rustup update
      - name: Rust Version
        run: rustc --version
      - uses: cargo-prebuilt/cargo-prebuilt-action@v1
        with:
          tools: cross
      - name: Build crate
        working-directory: ./build
        run: cross +stable build --verbose --release --locked --target ${{ matrix.target }} %%FLAGS%%
      - name: Collect
        run: ./scripts/collect.py ${{ matrix.target }} ./build/target/${{ matrix.target }}/release ${{ env.bins }}
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: target-${{ matrix.target }}
          path: |
            ${{ matrix.target }}.tar.gz
            ${{ matrix.target }}.sha256

  t2-pc-windows-msvc:
    if: %%T2_WIN_HAS_TARGETS%%
    strategy:
      fail-fast: false
      matrix:
        target: [ %%T2_WIN_TARGETS%% ]
    runs-on: windows-latest
    needs: [ setup ]
    steps:
      - uses: actions/checkout@v3
      - name: Get deps and crates from cache
        uses: actions/cache@v3
        with:
          path: |
            bundle
            build
          key: ${{ env.crate }}-${{ env.version }}-stable-deps
          enableCrossOsArchive: true
          fail-on-cache-miss: true
      - name: Move deps
        run: mv ./bundle/* ~/.cargo
      - uses: actions/cache@v3
        if: ${{ !%%IF%% }}
        with:
          path: |
            build/target
          key: ${{ runner.os }}-${{ env.crate }}-${{ env.version }}-stable-${{ matrix.target }}
      - name: Update Rust
        run: rustup update
      - name: Rust Version
        run: rustc --version
      - name: Add Rust target
        run: rustup target add ${{ matrix.target }}
      - uses: cargo-prebuilt/cargo-prebuilt-action@v1
        with:
          tools: cargo-auditable
      - name: Build crate
        working-directory: ./build
        run: cargo +stable auditable build --verbose --release --locked --target ${{ matrix.target }} %%FLAGS%%
      - name: Collect
        run: python3  ./scripts/collect.py ${{ matrix.target }} ./build/target/${{ matrix.target }}/release ${{ env.bins }}
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: target-${{ matrix.target }}
          path: |
            ${{ matrix.target }}.tar.gz
            ${{ matrix.target }}.sha256

  t3-cross:
    if: %%T3_CROSS_HAS_TARGETS%%
    strategy:
      fail-fast: false
      matrix:
        target: [ %%T3_CROSS_TARGETS%% ]
    env:
      CROSS_CONFIG: ../Cross.toml
    runs-on: ubuntu-latest
    needs: [ setup ]
    steps:
      - uses: actions/checkout@v3
      - name: Get deps and crates from cache
        uses: actions/cache@v3
        with:
          path: |
            bundle
            build
          key: ${{ env.crate }}-${{ env.version }}-stable-deps
          enableCrossOsArchive: true
          fail-on-cache-miss: true
      - name: Move deps
        run: mv ./bundle/* ~/.cargo
      - uses: actions/cache@v3
        if: ${{ !%%IF%% }}
        with:
          path: |
            build/target
          key: ${{ runner.os }}-${{ env.crate }}-${{ env.version }}-stable-${{ matrix.target }}
      - name: Update Rust
        run: rustup update
      - name: Rust Version
        run: rustc --version
      - uses: cargo-prebuilt/cargo-prebuilt-action@v1
        with:
          tools: cross
      - name: Build crate
        working-directory: ./build
        run: cross +stable build --verbose --release --locked --target ${{ matrix.target }} %%FLAGS%%
      - name: Collect
        run: ./scripts/collect.py ${{ matrix.target }} ./build/target/${{ matrix.target }}/release ${{ env.bins }}
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: target-${{ matrix.target }}
          path: |
            ${{ matrix.target }}.tar.gz
            ${{ matrix.target }}.sha256

  push-index:
    if: ${{ %%IF%% && always() && !contains(needs.*.result, 'cancelled') && !contains(needs.setup.result, 'failure') && !contains(needs.reports.result, 'failure') && !contains(needs.t1-cross.result, 'failure') && !contains(needs.t1-apple-darwin.result, 'failure') && !contains(needs.t2-cross.result, 'failure') && !contains(needs.t2-pc-windows-msvc.result, 'failure') }}
    runs-on: ubuntu-latest
    needs: [ setup, reports, t1-cross, t1-apple-darwin, t2-cross, t2-pc-windows-msvc, t3-cross ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: Create and push artifacts to release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.crate }}-${{ env.version }}
          name: ${{ env.crate }}-${{ env.version }}
          allowUpdates: true
          prerelease: true
          artifacts: "reports/*.report,target-*/*.tar.gz,target-*/*.sha256"
          body: ""
      - name: Create index file
        run: echo "${{ env.version }}" > ${{ env.crate }}
      - name: Push to index
        uses: svenstaro/upload-release-action@2.6.1
        with:
          tag: stable-index
          overwrite: true
          file: ${{ env.crate }}
      - name: DBG - API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /rate_limit

  banned-index:
    if: ${{ always() && !contains(needs.*.result, 'cancelled') && !contains(needs.setup.result, 'failure') && !contains(needs.reports.result, 'failure') && (contains(needs.t1-cross.result, 'failure') || contains(needs.t1-apple-darwin.result, 'failure') || contains(needs.t2-cross.result, 'failure') || contains(needs.t2-pc-windows-msvc.result, 'failure')) }}
    runs-on: ubuntu-latest
    needs: [ setup, reports, t1-cross, t1-apple-darwin, t2-cross, t2-pc-windows-msvc, t3-cross ]
    steps:
      - uses: actions/checkout@v3
      - name: Create index file
        run: echo "${{ env.version }}" > ${{ env.crate }}
      - name: Push to index
        uses: svenstaro/upload-release-action@2.6.1
        with:
          tag: banned-index
          file: ${{ env.crate }}
      - name: DBG - API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /rate_limit

  track-index:
    if: ${{ always() && !contains(needs.*.result, 'cancelled') && contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-latest
    needs: [ setup, reports, t1-cross, t1-apple-darwin, t2-cross, t2-pc-windows-msvc, t3-cross ]
    steps:
      - uses: actions/checkout@v3
      - name: Create index file
        run: echo "${{ env.version }}" > ${{ env.crate }}
      - name: Push to index
        uses: svenstaro/upload-release-action@2.6.1
        with:
          tag: track-index
          file: ${{ env.crate }}
      - name: DBG - API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /rate_limit
