[info]
id = "cargo-semver-checks"
git = "https://github.com/obi1kenobi/cargo-semver-checks"
unsupported = [
    "x86_64-unknown-netbsd",
    "x86_64-unknown-illumos",
    "x86_64-sun-solaris"
]
bins = ["cargo-semver-checks"]
