[info]
id = "cargo-supply-chain"
git = "https://github.com/rust-secure-code/cargo-supply-chain"
unsupported = [
    "riscv64gc-unknown-linux-gnu",
    "s390x-unknown-linux-gnu",
    "aarch64-pc-windows-msvc",
    "powerpc64-unknown-linux-gnu",
    "powerpc64le-unknown-linux-gnu",
]
bins = ["cargo-supply-chain"]
