[info]
id = "cargo-audit"
git = "https://github.com/rustsec/rustsec/tree/main/cargo-audit"
unsupported = [
    "riscv64gc-unknown-linux-gnu",
    "s390x-unknown-linux-gnu",
    "aarch64-pc-windows-msvc",
    "x86_64-sun-solaris",
    "powerpc64-unknown-linux-gnu",
    "powerpc64le-unknown-linux-gnu",
]
bins = ["cargo-audit"]
