[info]
id = "cargo-bom"
git = "https://github.com/sensorfu/cargo-bom"
unsupported = ["riscv64gc-unknown-linux-gnu", "x86_64-unknown-illumos"]
bins = ["cargo-bom"]

[target.all]
features = "cargo/vendored-openssl"
