[info]
id = "cargo-prebuilt"
git = "https://github.com/cargo-prebuilt/cargo-prebuilt"
unsupported = []
bins = ["cargo-prebuilt"]

[target.all]
features = "--features default-native"
no-default-features = true
