[info]
id = "cargo-clone"
git = "https://github.com/JanLikar/cargo-clone"
unsupported = []
bins = ["cargo-clone"]

[target.apple]
features = "vendored-openssl"

[target.windows]
features = "vendored-openssl"
