[info]
id = "cargo-binstall"
git = "https://github.com/cargo-bins/cargo-binstall"
unsupported = [
  "riscv64gc-unknown-linux-gnu",
  "s390x-unknown-linux-gnu",
  "powerpc64le-unknown-linux-gnu",
  "aarch64-pc-windows-msvc",
  "x86_64-unknown-freebsd",
  "x86_64-unknown-netbsd",
  "powerpc64-unknown-linux-gnu",
]
bins = ["cargo-binstall"]
