[info]
id = "cargo-generate"
git = "https://github.com/cargo-generate/cargo-generate"
unsupported = []
bins = ["cargo-generate"]

[target.apple]
features = "vendored-openssl"

[target.windows]
features = "vendored-openssl"
