[info]
id = "cargo-bom"
git = "https://github.com/sensorfu/cargo-bom"
unsupported = ["x86_64-unknown-illumos", "x86_64-sun-solaris"]
bins = ["cargo-bom"]

[target.all]
features = "cargo/vendored-openssl"
