[info]
id = "cargo-bitbake"
git = "https://github.com/meta-rust/cargo-bitbake"
unsupported = ["riscv64gc-unknown-linux-musl"]
bins = ["cargo-bitbake"]

[target.all]
features = "cargo/vendored-openssl"
