[info]
id = "coreutils"
git = "https://github.com/uutils/coreutils"
unsupported = []
bins = ["coreutils"]

[target.apple]
features = "unix"

[target.linux]
features = "unix"

[target.windows]
features = "windows"
