[info]
id = "erdtree"
git = "https://github.com/solidiquis/erdtree"
unsupported = [
  "x86_64-unknown-freebsd",
  "x86_64-pc-windows-msvc",
  "aarch64-pc-windows-msvc",
  "x86_64-unknown-illumos",
]
bins = ["erd"]
