[info]
id = "exa"
git = "https://github.com/ogham/exa"
unsupported = [
    "x86_64-pc-windows-msvc",
    "aarch64-pc-windows-msvc",
    "x86_64-unknown-illumos",
    "x86_64-sun-solaris",
    "mips64-unknown-linux-muslabi64",
    "mips64el-unknown-linux-muslabi64"
]
bins = ["exa"]

[target.all]
features = "vendored-openssl"
