[info]
id = "matrix-commander"
git = "https://github.com/8go/matrix-commander-rs"
unsupported = [
    "riscv64gc-unknown-linux-gnu",
    "s390x-unknown-linux-gnu",
    "aarch64-pc-windows-msvc",
    "x86_64-unknown-illumos",
    "x86_64-sun-solaris",
    "powerpc64-unknown-linux-gnu",
    "powerpc64le-unknown-linux-gnu",
]
bins = ["matrix-commander-rs"]

[target.all]
features = "reqwest/native-tls-vendored"
