[info]
id = "mise"
git = "https://github.com/jdx/mise"
unsupported = ["x86_64-unknown-freebsd", "x86_64-unknown-netbsd"]
bins = ["mise"]

[target.all]
features = "rustls,vfox/vendored-lua,openssl/vendored"
no-default-features = true
