[info]
id = "nu"
git = "https://github.com/nushell/nushell"
unsupported = [
    "x86_64-unknown-netbsd",
    "x86_64-unknown-illumos",
    "x86_64-sun-solaris",
]
bins = ["nu"]

[target.all]
features = "static-link-openssl,mimalloc"
