[info]
id = "nu"
git = "https://github.com/nushell/nushell"
unsupported = [
    "x86_64-unknown-freebsd",
    "x86_64-unknown-netbsd",
    "x86_64-unknown-illumos",
]
bins = ["nu"]

[target.all]
features = "mimalloc"
