[info]
id = "spacedisplay"
git = "https://github.com/funbiscuit/spacedisplay-rs"
unsupported = [
  "armv7-unknown-linux-gnueabihf",
  "armv7-unknown-linux-musleabihf",
  "x86_64-unknown-freebsd",
  "x86_64-unknown-netbsd",
]
bins = ["spacedisplay"]
