[info]
id = "spacedisplay"
git = "https://github.com/funbiscuit/spacedisplay-rs"
unsupported = [
    "x86_64-unknown-freebsd",
    "armv7-unknown-linux-gnueabihf",
    "armv7-unknown-linux-musleabihf",
    "x86_64-unknown-netbsd",
    "x86_64-unknown-illumos",
    "x86_64-sun-solaris",
]
bins = ["spacedisplay"]
