[info]
id = "sqlx-cli"
git = "https://github.com/launchbadge/sqlx"
unsupported = []
bins = ["sqlx", "cargo-sqlx"]

[target.all]
features = "postgres,sqlite,mysql,completions,rustls"
no-default-features = true
