[info]
id = "sqlx-cli"
git = "https://github.com/launchbadge/sqlx"
unsupported = [
    "x86_64-sun-solaris",
    "mips64-unknown-linux-muslabi64",
    "mips64el-unknown-linux-muslabi64"
]
bins = ["sqlx", "cargo-sqlx"]

[target.all]
features = "openssl-vendored"
