[info]
id = "tauri-cli"
git = "https://github.com/tauri-apps/tauri"
unsupported = [
    "x86_64-unknown-freebsd",
    "x86_64-unknown-netbsd",
    "x86_64-unknown-illumos",
]
bins = ["cargo-tauri"]

[target.all]
features = "native-tls-vendored"
no-default-features = true
