[info]
id = "wasm-pack"
git = "https://github.com/rustwasm/wasm-pack"
unsupported = [
    "riscv64gc-unknown-linux-gnu",
    "s390x-unknown-linux-gnu",
    "aarch64-pc-windows-msvc",
    "x86_64-unknown-illumos",
    "powerpc64-unknown-linux-gnu",
    "powerpc64le-unknown-linux-gnu",
]
bins = ["wasm-pack"]
