[info]
id = "watchexec-cli"
git = "https://github.com/watchexec/watchexec"
unsupported = [
    "s390x-unknown-linux-gnu",
    "x86_64-unknown-illumos",
    "x86_64-sun-solaris"
]
bins = ["watchexec"]
