[info]
id = "websocat"
git = "https://github.com/vi/websocat"
unsupported = ["aarch64-pc-windows-msvc", "riscv64gc-unknown-linux-musl"]
bins = ["websocat"]

[target.all]
features = "vendored_openssl"
