[info]
id = "wthrr"
git = "https://github.com/tobealive/wthrr-the-weathercrab"
unsupported = ["x86_64-unknown-illumos", "x86_64-sun-solaris"]
bins = ["wthrr"]

[target.all]
features = "reqwest/native-tls-vendored"
