[info]
id = "zellij"
git = "https://github.com/zellij-org/zellij"
unsupported = [
  "riscv64gc-unknown-linux-musl",
  "s390x-unknown-linux-gnu",
  "powerpc64le-unknown-linux-gnu",
  "armv7-unknown-linux-gnueabihf",
  "armv7-unknown-linux-musleabihf",
  "x86_64-pc-windows-msvc",
  "aarch64-pc-windows-msvc",
  "x86_64-unknown-freebsd",
  "x86_64-unknown-netbsd",
  "powerpc64-unknown-linux-gnu",
]
bins = ["zellij"]
