name: trunk

on:
  push:
    branches: [ main ]
    paths: [ .github/workflows/trunk.yml ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
#  schedule:
#    - cron: '0 6 * * *'

# imgs: &imgs [ rust, node, rustnode ]
# archs: &archs [ amd64, arm64 ]
# distros: &distros [ debian-latest, debian-bullseye-slim, debian-buster, debian-buster-slim, ubuntu-latest, ubuntu-focal ] # alpine-latest, alpine-3.15, alpine-3.14,
# node_versions: &node_versions [ node, --lts ]

env:
  stable-index: https://github.com/crow-rest/binary-cargo-tools/releases/download/stable-index/
  nightly-index: https://github.com/crow-rest/binary-cargo-tools/releases/download/nightly-index/
  crate: trunk
  repo: https://github.com/thedodd/trunk.git
  license: LICENSE-APACHE,LICENSE-MIT
  bins: trunk

jobs:
  # Stable
  stable-check:
    outputs:
      crate-version: ${{ steps.check.outputs.version }}
      crate-download: ${{ steps.check.outputs.dl }}
      create-hash: ${{ steps.check.outputs.hash }}
      build: ${{ steps.check.outputs.build }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ahmadnassri/action-workflow-queue@v1
      - uses: actions/cache@v3
        with:
          path: |
            ${{ env.crate }}.cache
          key: stable-${{ env.crate }}-${{ env.repo }}-${{ secrets.CACHE_VERSION }}
      - name: Check and Configure
        id: check
        run: ./check.py stable ${{ env.stable-index }} ${{ env.crate }}

  stable-test:
    needs: [ stable-check ]
    env:
      CRATE_VERSION: ${{ needs.stable-check.outputs.crate-version }}
      CRATE_DOWNLOAD: ${{ needs.stable-check.outputs.crate-download }}
      CRATE_HASH: ${{ needs.stable-check.outputs.crate-hash }}
      BUILD: ${{ needs.stable-check.outputs.build }}
    runs-on: ubuntu-latest
    steps:
      - name: Test Echo
        run: |
          echo $CRATE_VERSION
          echo $CRATE_DOWNLOAD
          echo $CRATE_HASH
          echo $BUILD

  # Nightly
  
  # OLD
